version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      codemirror:
        patterns:
          - "@codemirror/*"
          - "@bhsd/codemirror-wikitext"
      testing:
        patterns:
          - "vitest"
          - "@testing-library/*"
          - "@playwright/test"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
