import type { SupportedLocale } from "./locales.js";

export interface MessageCatalog {
  // Brand
  "brand.name": string;
  "brand.tagline": string;

  // Language selector
  "language.label": string;
  "language.follow-browser": string;
  "language.en": string;
  "language.zh-Hans": string;
  "language.zh-Hant": string;

  // Theme selector
  "theme.label": string;
  "theme.system": string;
  "theme.light": string;
  "theme.dark": string;

  // Header links
  "header.core": string;
  "header.frontend": string;

  // Initialization screen
  "init.initializing": string;
  "init.retry-worker": string;

  // Toolbar
  "toolbar.aria-label": string;
  "toolbar.format": string;
  "toolbar.stop": string;
  "toolbar.copy-output": string;
  "toolbar.download": string;
  "toolbar.open-file": string;
  "toolbar.clear": string;
  "toolbar.load-example": string;
  "toolbar.settings": string;
  "toolbar.diff": string;

  // Source editor
  "editor.source.label": string;
  "editor.source.muted": string;
  "editor.output.label": string;
  "editor.output.muted": string;
  "editor.stats.aria": string;

  // EditorPane misc
  "editor.file-not-readable": string;
  "editor.large-file-warning": string;

  // Diff view
  "diff.title": string;
  "diff.side-by-side": string;
  "diff.unified": string;
  "diff.original.aria": string;
  "diff.formatted.aria": string;
  "diff.unified.aria": string;
  "diff.loading": string;

  // Status bar
  "status.ready": string;
  "status.formatting": string;
  "status.changed": string;
  "status.unchanged": string;
  "status.fail-closed": string;
  "status.unexpected-error": string;
  "status.profile": string;
  "status.versions": string;

  // Privacy
  "privacy.notice": string;

  // Diagnostics
  "diagnostics.title": string;
  "diagnostics.entries": string;
  "diagnostics.empty": string;
  "diagnostics.table.rule": string;
  "diagnostics.table.severity": string;
  "diagnostics.table.message": string;
  "diagnostics.severity.warning": string;
  "diagnostics.severity.info": string;
  "diagnostics.stage": string;
  "diagnostics.aria": string;

  // Settings panel
  "settings.title": string;
  "settings.close": string;
  "settings.general": string;
  "settings.profile": string;
  "settings.profile.default": string;
  "settings.profile.production": string;
  "settings.profile.aggressive": string;
  "settings.line-width": string;
  "settings.formatting-level": string;
  "settings.level.safe": string;
  "settings.level.normal": string;
  "settings.level.experimental": string;
  "settings.wrap-lines": string;
  "settings.templates": string;
  "settings.format-templates": string;
  "settings.inline-spacing": string;
  "settings.inline-spacing.auto": string;
  "settings.inline-spacing.compact": string;
  "settings.inline-spacing.spaced": string;
  "settings.parameter-layout": string;
  "settings.parameter-layout.compact": string;
  "settings.parameter-layout.flush": string;
  "settings.parameter-layout.indented": string;
  "settings.format-template-params": string;
  "settings.tables": string;
  "settings.format-tables": string;
  "settings.cell-separator": string;
  "settings.cell-separator.auto": string;
  "settings.cell-separator.split": string;
  "settings.cell-separator.preserve": string;
  "settings.structure": string;
  "settings.headings": string;
  "settings.lists": string;
  "settings.section-spacing": string;
  "settings.normalize-blank-lines": string;
  "settings.html-void-tags": string;
  "settings.html-void-tags.html5": string;
  "settings.html-void-tags.xhtml": string;
  "settings.html-void-tags.preserve": string;
  "settings.links-metadata": string;
  "settings.categories": string;
  "settings.file-links": string;
  "settings.wikilinks": string;
  "settings.external-links": string;
  "settings.references": string;
  "settings.redirects": string;
  "settings.behavior-switches": string;
  "settings.interlanguage-links": string;
  "settings.interlanguage-placement": string;
  "settings.interlanguage-placement.preserve": string;
  "settings.interlanguage-placement.footer": string;
  "settings.behavior-switch-placement": string;
  "settings.behavior-switch-placement.preserve": string;
  "settings.behavior-switch-placement.footer": string;
  "settings.interlanguage-prefixes": string;
  "settings.parser-config": string;
  "settings.parser-config.value": string;
  "settings.restore-core-defaults": string;
  "settings.reset-settings": string;

  // Formatter status
  "status.worker-not-ready": string;
  "status.source-changed": string;
  "status.formatting-stopped": string;

  // Clipboard and copy
  "copy.success": string;
  "copy.denied": string;

  // Result summary — generated by summarizeRuleDiagnostics
  "summary.templates-changed": string;
  "summary.templates-skipped": string;
  "summary.tables-changed": string;
  "summary.tables-skipped": string;
  "summary.lists-changed": string;
  "summary.categories-moved": string;
  "summary.redirects-formatted": string;
  "summary.file-links-formatted": string;
  "summary.wikilinks-formatted": string;
  "summary.external-links-formatted": string;
  "summary.references-formatted": string;
  "summary.section-spacing-normalized": string;
  "summary.equivalence-failed": string;

  // Document title and meta
  "document.title.default": string;
  "document.title.example": string;
  "meta.description": string;
  "meta.og-title": string;
  "meta.og-description": string;

  // Universal plural forms (English only: one / other)
  "plural.templates": string;
  "plural.tables": string;
  "plural.list-lines": string;
  "plural.categories": string;
  "plural.file-links": string;
  "plural.wikilinks": string;
  "plural.external-links": string;
  "plural.references": string;
  "plural.entries": string;

  // Generic
  "generic.unexpected-error": string;
}

export const enMessages: MessageCatalog = {
  // Brand
  "brand.name": "Wikitext Formatter",
  "brand.tagline": "Safe, local MediaWiki source formatting",

  // Language selector
  "language.label": "Language",
  "language.follow-browser": "Follow browser",
  "language.en": "English",
  "language.zh-Hans": "简体中文",
  "language.zh-Hant": "繁體中文",

  // Theme selector
  "theme.label": "Theme",
  "theme.system": "System",
  "theme.light": "Light",
  "theme.dark": "Dark",

  // Header links
  "header.core": "Core",
  "header.frontend": "Frontend",

  // Initialization screen
  "init.initializing": "Initializing the local formatter Worker…",
  "init.retry-worker": "Retry Worker",

  // Toolbar
  "toolbar.aria-label": "Formatter actions",
  "toolbar.format": "Format",
  "toolbar.stop": "Stop",
  "toolbar.copy-output": "Copy output",
  "toolbar.download": "Download",
  "toolbar.open-file": "Open file",
  "toolbar.clear": "Clear",
  "toolbar.load-example": "Load example",
  "toolbar.settings": "Settings",
  "toolbar.diff": "Diff",

  // Source editor
  "editor.source.label": "Source",
  "editor.source.muted": "Wikitext",
  "editor.output.label": "Formatted output",
  "editor.output.muted": "Read-only",
  "editor.stats.aria": "{lines} lines, {characters} characters",

  // EditorPane misc
  "editor.file-not-readable":
    "The selected file could not be read in this browser.",
  "editor.large-file-warning":
    "This is an unusually large file. Formatting may take longer; you can stop the Worker at any time.",

  // Diff view
  "diff.title": "Original and formatted diff",
  "diff.side-by-side": "Side-by-side view",
  "diff.unified": "Unified view",
  "diff.original.aria": "Original Wikitext",
  "diff.formatted.aria": "Formatted Wikitext",
  "diff.unified.aria": "Unified Wikitext diff",
  "diff.loading": "Loading diff tools…",

  // Status bar
  "status.ready": "Ready",
  "status.formatting": "Formatting…",
  "status.changed": "Formatted with changes",
  "status.unchanged": "Already formatted",
  "status.fail-closed": "Fail-closed",
  "status.unexpected-error": "Unexpected error",
  "status.profile": "Profile",
  "status.versions": "Web {web} · Formatter {fmt}",

  // Privacy
  "privacy.notice":
    "Formatting runs locally in your browser. Your Wikitext is not uploaded.",

  // Diagnostics
  "diagnostics.title": "Diagnostics",
  "diagnostics.entries":
    "{count} rule {count, plural, one {entry} other {entries}}",
  "diagnostics.empty":
    "No failures, warnings, or rule diagnostics for the latest result.",
  "diagnostics.table.rule": "Rule",
  "diagnostics.table.severity": "Severity",
  "diagnostics.table.message": "Message",
  "diagnostics.severity.warning": "warning",
  "diagnostics.severity.info": "info",
  "diagnostics.stage": "Stage",
  "diagnostics.aria": "Diagnostic details",

  // Settings panel
  "settings.title": "Formatter settings",
  "settings.close": "Close settings",
  "settings.general": "General",
  "settings.profile": "Profile",
  "settings.profile.default": "Default",
  "settings.profile.production": "Production",
  "settings.profile.aggressive": "Aggressive",
  "settings.line-width": "Line width",
  "settings.formatting-level": "Formatting level",
  "settings.level.safe": "Safe",
  "settings.level.normal": "Normal",
  "settings.level.experimental": "Experimental",
  "settings.wrap-lines": "Wrap long lines",
  "settings.templates": "Templates",
  "settings.format-templates": "Format templates",
  "settings.inline-spacing": "Inline spacing",
  "settings.inline-spacing.auto": "Auto",
  "settings.inline-spacing.compact": "Compact",
  "settings.inline-spacing.spaced": "Spaced",
  "settings.parameter-layout": "Parameter layout",
  "settings.parameter-layout.compact": "Compact",
  "settings.parameter-layout.flush": "Flush",
  "settings.parameter-layout.indented": "Indented",
  "settings.format-template-params":
    "Format template parameters (experimental)",
  "settings.tables": "Tables",
  "settings.format-tables": "Format tables",
  "settings.cell-separator": "Cell separator",
  "settings.cell-separator.auto": "Auto",
  "settings.cell-separator.split": "Split",
  "settings.cell-separator.preserve": "Preserve",
  "settings.structure": "Structure",
  "settings.headings": "Headings",
  "settings.lists": "Lists",
  "settings.section-spacing": "Section spacing",
  "settings.normalize-blank-lines": "Normalize blank lines",
  "settings.html-void-tags": "HTML void tags",
  "settings.html-void-tags.html5": "HTML5",
  "settings.html-void-tags.xhtml": "XHTML",
  "settings.html-void-tags.preserve": "Preserve",
  "settings.links-metadata": "Links and metadata",
  "settings.categories": "Categories",
  "settings.file-links": "File links",
  "settings.wikilinks": "Wikilinks",
  "settings.external-links": "External links",
  "settings.references": "References",
  "settings.redirects": "Redirects",
  "settings.behavior-switches": "Behavior switches",
  "settings.interlanguage-links": "Interlanguage links",
  "settings.interlanguage-placement": "Interlanguage placement",
  "settings.interlanguage-placement.preserve": "Preserve",
  "settings.interlanguage-placement.footer": "Footer",
  "settings.behavior-switch-placement": "Behavior-switch placement",
  "settings.behavior-switch-placement.preserve": "Preserve",
  "settings.behavior-switch-placement.footer": "Footer",
  "settings.interlanguage-prefixes": "Interlanguage prefixes",
  "settings.parser-config": "Parser configuration",
  "settings.parser-config.value": "MediaWiki bundled browser configuration",
  "settings.restore-core-defaults": "Restore core defaults",
  "settings.reset-settings": "Reset settings",

  // Formatter status
  "status.worker-not-ready": "The formatter Worker is not ready.",
  "status.source-changed":
    "The source changed while formatting. The older result was discarded; format again to update the output.",
  "status.formatting-stopped":
    "Formatting was stopped. The formatter Worker was restarted.",

  // Clipboard and copy
  "copy.success": "Formatted output copied to the clipboard.",
  "copy.denied":
    "Clipboard access was denied. Select and copy the output manually.",

  // Result summary — generated by summarizeRuleDiagnostics
  "summary.templates-changed":
    "{count, plural, one {Formatted # template.} other {Formatted # templates.}}",
  "summary.templates-skipped":
    "{count, plural, one {Skipped # ambiguous template.} other {Skipped # ambiguous templates.}}",
  "summary.tables-changed":
    "{count, plural, one {Formatted # table.} other {Formatted # tables.}}",
  "summary.tables-skipped":
    "{count, plural, one {Skipped # ambiguous table.} other {Skipped # ambiguous tables.}}",
  "summary.lists-changed":
    "{count, plural, one {Formatted # list line.} other {Formatted # list lines.}}",
  "summary.categories-moved":
    "{count, plural, one {Moved # category.} other {Moved # categories.}}",
  "summary.redirects-formatted": "Formatted the redirect directive.",
  "summary.file-links-formatted":
    "{count, plural, one {Formatted # file link.} other {Formatted # file links.}}",
  "summary.wikilinks-formatted":
    "{count, plural, one {Formatted # wikilink.} other {Formatted # wikilinks.}}",
  "summary.external-links-formatted":
    "{count, plural, one {Formatted # external link.} other {Formatted # external links.}}",
  "summary.references-formatted":
    "{count, plural, one {Formatted # reference.} other {Formatted # references.}}",
  "summary.section-spacing-normalized":
    "Normalized spacing around section headings.",
  "summary.equivalence-failed": "{structure} equivalence was not demonstrated.",

  // Document title and meta
  "document.title.default": "Wikitext Formatter",
  "document.title.example": "Example — Wikitext Formatter",
  "meta.description":
    "A browser-based formatter for MediaWiki Wikitext. Formatting runs locally and source text is never uploaded.",
  "meta.og-title": "Wikitext Formatter",
  "meta.og-description": "A browser-based formatter for MediaWiki Wikitext",

  // Universal plural forms
  "plural.templates": "{count, plural, one {template} other {templates}}",
  "plural.tables": "{count, plural, one {table} other {tables}}",
  "plural.list-lines": "{count, plural, one {list line} other {list lines}}",
  "plural.categories": "{count, plural, one {category} other {categories}}",
  "plural.file-links": "{count, plural, one {file link} other {file links}}",
  "plural.wikilinks": "{count, plural, one {wikilink} other {wikilinks}}",
  "plural.external-links":
    "{count, plural, one {external link} other {external links}}",
  "plural.references": "{count, plural, one {reference} other {references}}",
  "plural.entries": "{count, plural, one {entry} other {entries}}",

  // Generic
  "generic.unexpected-error": "Unexpected formatter error",
};

// Also export as `messages` for the catalog map in I18nProvider.
export const messages = enMessages;

export const locale: SupportedLocale = "en";
